CREATE DATABASE Catalog;

CREATE TABLE Item (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  genre INT NOT NULL,
  label INT NOT NULL,
  author INT NOT NULL,
  source INT NOT NULL,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  FOREIGN KEY (label) REFERENCES Label (id),
);

CREATE TABLE Label (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  color VARCHAR(50) NOT NULL,
)

CREATE TABLE Book ( 
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
  publisher VARCHAR(50) NOT NULL, 
  cover_state VARCHAR(7) NOT NULL, 
  FOREIGN KEY (id) REFERENCES Item (id), 
);